# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_yvw4dCulO2Mz@ep-green-bonus-ac2lyel6-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yvw4dCulO2Mz

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Configurações do Servidor
server.port=8080
server.servlet.context-path=/api